import { writeFileSync } from "node:fs";
import type { AuditReasoning, ReasonedFinding } from "./reasoner.js";

const severityOrder: Record<string, number> = {
  Critical: 0,
  High: 1,
  Medium: 2,
  Low: 3,
  Informational: 4,
};

function renderFinding(f: ReasonedFinding): string {
  return `### ${f.title}
**Severity:** ${f.severity}

${f.plainEnglishExplanation}

**Suggested fix:**
${f.suggestedFix}
`;
}

export function generateMarkdownReport(
  contractName: string,
  reasoning: AuditReasoning,
  outputPath: string
): void {
  const allFindings = [...reasoning.staticFindingsExplained, ...reasoning.businessLogicRisks].sort(
    (a, b) => (severityOrder[a.severity] ?? 5) - (severityOrder[b.severity] ?? 5)
  );

  const counts = allFindings.reduce<Record<string, number>>((acc, f) => {
    acc[f.severity] = (acc[f.severity] ?? 0) + 1;
    return acc;
  }, {});

  const summaryLine = Object.entries(counts)
    .sort((a, b) => (severityOrder[a[0]] ?? 5) - (severityOrder[b[0]] ?? 5))
    .map(([sev, count]) => `${sev}: ${count}`)
    .join(" · ");

  const md = `# Security Audit Report — ${contractName}

_Generated by AI Contract Auditor (Slither + GPT-5.6 via Codex)_

## Summary

${reasoning.contractSummary}

**Findings overview:** ${summaryLine || "No findings"}

## Static Analysis Findings (explained)

${reasoning.staticFindingsExplained.length ? reasoning.staticFindingsExplained.map(renderFinding).join("\n") : "_No static findings reported by Slither._\n"}

## Business Logic & Economic Risk Review

${reasoning.businessLogicRisks.length ? reasoning.businessLogicRisks.map(renderFinding).join("\n") : "_No additional risks identified in this pass._\n"}

---
*This report is AI-assisted and does not replace a professional manual audit. Use it as a first-pass triage tool.*
`;

  writeFileSync(outputPath, md, "utf-8");
}
